<a href="https://www.kaggle.com/code/iremakdogan/python-basics?scriptVersionId=167739236" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

These are simple exercises for Python Programming in Scientific Computing

I am following Advanced Pyton Programming course of Mike X Cohen on Udemy

Section 1 - Basics

## New type variable: List with []


In [2]:
aList = [0, 1, 2, 3, 4, 5]
%whos
strList = ["hi", "my", "name", "is", "irem"]
mixList = ["hello", 30]

embedList = [3, [1,2, 'three'], [4,5]]
#  hard to follow list elements, lets dibide them into lines
embedList = [3,
            [1,2, 'three'], # a list 
            [4,5]
            ]
embedList

Variable    Type      Data/Info
-------------------------------
aList       list      n=6
dirname     str       /kaggle/input
filenames   list      n=0
os          module    <module 'os' from '/opt/c<...>da/lib/python3.10/os.py'>


[3, [1, 2, 'three'], [4, 5]]

Working with lists:

In [3]:
4 in aList # this is a question to ask whether aList includes 4 in itself -> return True or False
4.5 not in aList # we can use "not in" also

print(aList)
print(strList)

aList + strList

aList * 3 # it repeats the list 3 times, not multiply the elements by 3 
# if you wanted to multiply individual elements, then you should use for loops or numpy arrays

[0, 1, 2, 3, 4, 5]
['hi', 'my', 'name', 'is', 'irem']


[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]

**Methods of Lists**

In [4]:
aList.append(-100) # whenever I run this code, it adds one more -100
print(aList)

aList.sort() # sort the list itself
print(aList)

newList = [1,5,6,3,2,7,7,7,7,7,3,9,13,34,0]
newList.count(7) # count how many 7s in the list

[0, 1, 2, 3, 4, 5, -100]
[-100, 0, 1, 2, 3, 4, 5]


5

## New type variable: Tuples with ()
What is the difference between List and Tuple? 
- List is mutable and Tuples are immutable
- Immutable means we cannot change it, once we created it, it is fixed anymore

In [5]:
aTuple = (3,4,3)
aList = [3,4,3]

print(aTuple)
print(aList)

aList[0] = 5 # mutable
# aTuple[0] = 5 # gives error

# but you can assign whole new Tuple
aTuple = (5,'hi', '5')
print(aTuple)

# we can convert tuples into list
newL = list(aTuple)
print(type(newL))
# once we changed it into list, we can change its elements
newL[0] = 'hello list'
print(newL)

(3, 4, 3)
[3, 4, 3]
(5, 'hi', '5')
<class 'list'>
['hello list', 'hi', '5']


Why we have both tuples nad list? why we need them?
- We can think of a tuple as being like a list that has a security measure on it. It has a lock on it. This would be if the information is really important and you don't want it to be modified by accident, maybe this is some original data and you want to make sure that the original data are never modified so you can store the original data as a tuple.
- Then when you need to grab a little bit of data, you need to select a little bit of data. Then you could select that piece of data and turn that into a list so you could continue working with it and changing it or running analysis on it.

**Booleans and Comparisons**

In [6]:
a = 4
b = 8
outcome = a*2 == b # short and clear assignment
print(outcome)

# numbers can be converted boolean
# the only number which is False is 0
# other numbers are True
bool(3543534.345345) # True
bool(0) # False
bool('irem')  # True
bool('') # False
bool(' ') # True

True


True

# New type variable: Dictionary with dict() and it has {}
If you are familiar with Matlab, then Dictionary is similar to Structure in Matlab

In [7]:
D = dict()
D # outputs empty dict as {}

{}

In [8]:
# key/value paits
D['name'] = 'Irem'
D['AgeRange'] = [20, 35]
D # it does not have specific order in keys 

{'name': 'Irem', 'AgeRange': [20, 35]}

In [9]:
# we can create dictionary directly
E = {'name': 'irem', 'ageRange': [20,35]}
E

print(E['name']) # calling with square braces like in the list and tuples

irem


In [10]:
print(D.keys())
print('Name' in D) # Returns False bec Keys are Case Sensitive
print('irem' in D) # Returns False bec actually irem is in Dic but this expression searches the Keys!
print(D.values())
print(D.items()) # all items but in a type of List

dict_keys(['name', 'AgeRange'])
False
False
dict_values(['Irem', [20, 35]])
dict_items([('name', 'Irem'), ('AgeRange', [20, 35])])


# Indexing
This is a way to extract specific items out of a list or an array or a string or almost every type of variable.

In [11]:
arange = range(5)
arange # type range from 0 to 5

range(0, 5)

In [12]:
alist = list(arange) # convert range to list
alist

[0, 1, 2, 3, 4]

In [13]:
# python starts counting from 0
# alist = alist + [1,4,0,78,4,5,23]
print(alist)
print(alist[-5])

idx = [3,4]
# alist[idx] # gives an error as indices must be integers or slices, not list

[0, 1, 2, 3, 4]
0


In [14]:
newList = [4,3.2,[1,2,3], 9,8] 
# lets retrieve the inner list
newList[2][1]

2

In [15]:
# indexing works similar in strings also
astr = 'hello'
print(astr[-5])

h


In [16]:
# we can put dictionary into list as well!
listlist = [4, 'hi', ['inner', 'list'], {'dict':1, 'inner': 'dict'}]
print(listlist)

[4, 'hi', ['inner', 'list'], {'dict': 1, 'inner': 'dict'}]


# Slicing

In [17]:
alist = list(range(0,19))
print(alist)
print(alist[0:2]) # second arguments is EXCLUDED
print(alist[2:6])
print(alist[10:]) # until the end
print(alist[:6]) # from the begining 

print(alist[0:10:2]) # third elements is the step size
print(alist[::3]) # gofrom begining to end in step size 3
print(alist[::-5]) # step backwards, it is like sorting in descending

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
[0, 1]
[2, 3, 4, 5]
[10, 11, 12, 13, 14, 15, 16, 17, 18]
[0, 1, 2, 3, 4, 5]
[0, 2, 4, 6, 8]
[0, 3, 6, 9, 12, 15, 18]
[18, 13, 8, 3]


# Functions

# Libraries
Python itself does not have many builtin functions which makes it very fast and light, and therefore we use libraries 

In [18]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Numpy

In [19]:
print(np.mean(alist)) # can use python list as input to numpy function

nparray = np.array(alist) # convert list to array
print(type(alist))
print(type(nparray))

nparray.mean() # since this is numpy array, we can call the function like this
np.mean(nparray) # this is okey also
# alist.mean() # but list object does not have builtin mean() function in python library
# this function belongs to numpy library, so we cannot call it like this
# but when the object itself is numpy type like np array, we can call it directly

9.0
<class 'list'>
<class 'numpy.ndarray'>


9.0

In [20]:
n = [1,4,5,7,8,9,6,4,2,4,5]
print(n)
n.sort() # this changes n itself even though we did not directly assign to itself
# but some functions does not do that - so we need to know the functions and this propert
print(n)

n = [1,4,5,7,8,9,6,4,2,4,5]
print(type(np.sort(n))) # np.sort() changes it into numpy array

[1, 4, 5, 7, 8, 9, 6, 4, 2, 4, 5]
[1, 2, 4, 4, 4, 5, 5, 6, 7, 8, 9]
<class 'numpy.ndarray'>


# Pandas
This library is important to store data in a table that is easy to work with and easy to look at and easy to extract information from and so on.

In [21]:
# create some random data
var1 = np.random.randn(100)*5 +20 # normal distribution
var2 = np.random.randn(100)>0 

# np.mean(var1)
labels = ["Temp. (C)", "Ice Cream Eaten"]

# create dictionary
D = {labels[0]:var1, labels[1]:var2} 
D # very hard to read

{'Temp. (C)': array([16.00240385, 17.580522  , 23.16905998, 22.63774121, 15.1052199 ,
        12.13954463, 11.42396796, 15.26416414, 24.3319558 , 22.75219926,
        21.26984779, 26.21125232, 25.4215616 , 26.46022409, 23.74425553,
         8.50832725, 19.18388941, 26.61613857, 16.90875676, 17.05141723,
        16.75477472, 17.16580827, 17.26853419, 23.33246476, 21.44552582,
        24.76497993, 21.33253896, 23.89384922, 17.37648798, 18.95884604,
        25.97474059, 18.30775216, 25.17155149, 27.85924213, 24.8173439 ,
        14.85240589, 19.56091136, 17.0769139 , 24.86639264, 26.41328568,
        26.59748537, 24.10675547, 17.42901108, 28.3137699 , 20.13774352,
        26.20371349, 22.01257757, 19.92676882, 22.99177229, 29.6722496 ,
        20.40450462, 24.90023003, 22.23650462, 20.8185476 , 29.03938227,
        30.06586496,  9.38487521, 15.16853338, 20.86446505, 19.13032594,
        26.80947263, 28.11654876, 25.13977731, 19.54584232, 25.45536745,
        18.79642457, 17.16945112, 20.0

In [22]:
# change dictionary into pandas dataframe
df = pd.DataFrame(data=D)
df # looks nice , default: first 5 rows and last 5 rows

Temp. (C)  Ice Cream Eaten
0   16.002404            False
1   17.580522             True
2   23.169060            False
3   22.637741            False
4   15.105220             True
..        ...              ...
95  21.937569            False
96  23.148462             True
97  33.019947             True
98  19.818874             True
99  20.042134             True

[100 rows x 2 columns]

In [23]:
df.head(12) # first 12 rows 

Temp. (C)  Ice Cream Eaten
0   16.002404            False
1   17.580522             True
2   23.169060            False
3   22.637741            False
4   15.105220             True
5   12.139545            False
6   11.423968            False
7   15.264164            False
8   24.331956             True
9   22.752199             True
10  21.269848            False
11  26.211252             True

In [24]:
df.count() # to check whether we have missing values in dataset

Temp. (C)          100
Ice Cream Eaten    100
dtype: int64

In [25]:
# exercise: create a pandas dataframe with three variables:
# 1) integers from 0 to 10
# 2) their square
# 3) their log

int_nums = np.array(range(1,11))
int_nums.mean()
D = {'integers': int_nums, 'squares': int_nums**2, 'logs': np.log(int_nums)}
df = pd.DataFrame(data=D)

df # if I write print(df), the output become in worse shape
# square_nums = np.square(int_nums) # I expect them to be writable as int_nums.square()
# log_nums = np.log(int_nums) # I expect them to be writable as int_nums.log()
# because int_num is a ndarray so it can call np objects directly
# explanation below:

integers  squares      logs
0         1        1  0.000000
1         2        4  0.693147
2         3        9  1.098612
3         4       16  1.386294
4         5       25  1.609438
5         6       36  1.791759
6         7       49  1.945910
7         8       64  2.079442
8         9       81  2.197225
9        10      100  2.302585

The difference in how you can call certain NumPy functions like `mean()` and `square()` is due to how they are implemented in NumPy.

1. **Direct method call (`a.mean()`)**: Some functions in NumPy are implemented as methods directly on NumPy arrays. These methods are designed to be convenient for common operations and often provide more functionality or customization options compared to their counterparts in the `np` namespace. For example, `mean()` is implemented as a method of NumPy arrays, allowing you to directly call `a.mean()` to compute the mean of the array `a`.

2. **Using `np` namespace (`np.square(a)`)**: Other functions in NumPy are implemented as standalone functions in the NumPy namespace (`np`). These functions are designed to work with various types of inputs, not just NumPy arrays. Therefore, you need to explicitly specify the input as an argument to the function when using it. For example, `np.square()` is a standalone function that computes the element-wise square of an array. To use it, you need to pass the array `a` as an argument: `np.square(a)`.

To determine which approach to use, you can consult the NumPy documentation or use auto-completion in your integrated development environment (IDE) or text editor. Typically, functions implemented as methods of NumPy arrays (like `mean()`, `sum()`, `max()`, etc.) are designed for convenience and readability when working directly with arrays, while functions in the `np` namespace are more general-purpose and can accept a wider range of inputs.

In [26]:
sum??

# Functions

In [27]:
def awasomeFunction(a,b):
    return a+b, a*b 

output = awasomeFunction(2,3) # if assign two reutrns in one variable, assign to a tuple
type(output)

output1, output2 = awasomeFunction(2,3) # this time, it becomes int


In [28]:
# Lambda functions - one line of functions 
# x is input, then : , then function definition
littlefun = lambda x : x**2 - 1

# OOP (Classes)

In [29]:
class Experiment(object):
    # constructor method
    def __init__(self, eType, dataN, status='ongoing'):
        self.exptTye = eType
        self.dataCount = dataN
        self.expStatus = status
        
    def increaseN(self, number):
        self.dataCount += number
        
    def __str__(self):
        return 'Experiment type ' + self.exptTye

myExperiment = Experiment('Brain', 1450)

In [30]:
for i in range(100):
    if i%2 == 0:
        continue  
    print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99


# Error Handling

In [31]:
# initializing variables
r = [] # empty list
rr = np.array([]) # empty array

# if you want to have 4x5 matrix:
# r = np.zeros(4,5) # but this will gives errors 
# bec in Numpy, size should be given in Tuples in first inpur
# in the second input, the type needs to be given

# r = np.zeros((4,5), ...) # now the first element is Tuple and the other inputs can take another values
# as we can see, tuples can be used like here, they do not have to be indicate list-type data structure always 

r = np.zeros((4,5))
r

# Although Matlab automatically increase the matrix size when we assign something, this does NOT happen in NP
# r[8,7] = 10 # this will gives error

# Exercise on 3 methods
# 1) list append
# 2) numpy append
# 3) numpy initialization

import time
t = [0]*3 # multipliying list gives us extended list
N = 10000

# list append  -> suprisingly FAST
r = [] 
tic = time.perf_counter()
for i in range(N):
    r.append(i**2)
t[0] = (time.perf_counter() - tic) * 1000

# numpy append  -> took HUGE time
r = np.array([]) # empty list
tic = time.perf_counter()
for i in range(N):
    r = np.append(r, i**2) 
t[1] = (time.perf_counter() - tic) * 1000

# numpy initialize -> fast as Lists
r = np.zeros(N)
tic = time.perf_counter()
for i in range(N):
    r[i] = i**2
t[2] = (time.perf_counter() - tic) * 1000

print(t)

# SOO - while working with Numpy arrays, it is best to initialize at the begining

[5.6334989999413665, 84.49611599985474, 6.490795999980037]


In [32]:
# error handling
def funfun(x,y):
    # check that inputs are numeric
    if not isinstance(x,(int, float)):
        if isinstance(x, str) and x.isnumeric(): # true for only the integer
            x = float(x)
        else:
            raise Exception('Input x must be a number')
    
    z = x*y
    print(z)
    
funfun(3,5)
funfun(3.0,5)
funfun('3',5)
funfun('3',5)

15
15.0
15.0
15.0


In [33]:
# multiple inputs with zip
# same length
someList = [3,4,5,6,7]
otherList = ['d', 'E', 'f', 'g', 'm', 'x']

for i,j in zip(someList, otherList):
    #print(i,j)
    pass
    

# different length
someList2 = [3,4,5,6,7,8,9]
otherList2 = ['d', 'E', 'f']

for i,j in zip(someList2, otherList2): # only goes until shorter list 
    print(i,j)

    
# we can create new list with zip()
z = list(zip(someList, otherList)) # creates list from tuples which is in 2D
# BUT funny feature, this only works one time, when we run one more time, it makes the list empty in MIKE's video but NOT here??
print(z)
print(z[0][1])

3 d
4 E
5 f
[(3, 'd'), (4, 'E'), (5, 'f'), (6, 'g'), (7, 'm')]
d


In [34]:
# single line for loops 
newList = ['Odd' if i%2 else 'even' for i in range(10)] # this will put the result in a list and assign to newList
print(newList)

newList2 = [print('Odd') if i%2 else print('even') for i in range(10)] # this prints in new line in each time but since it is print(), the newList is None
print(newList2)

['even', 'Odd', 'even', 'Odd', 'even', 'Odd', 'even', 'Odd', 'even', 'Odd']
even
Odd
even
Odd
even
Odd
even
Odd
even
Odd
[None, None, None, None, None, None, None, None, None, None]


# Broadcasting in Numpy
Important feature for Data Science and Linear Algebra

In [35]:
# question: how do we add W matrix to each row of X seperately?
# ----------------------------------------------------
# first solution
X = np.array([ [1,2,3],
             [2,3,4],
             [3,4,5],
             [4,5,6]  ])

w = np.array([10,20,30])

Y = X
Y = X + w # assigning to a new variable

print(X)
print(Y)

# ----------------------------------------------------
# second solution
X2 = np.array([ [1,2,3],
             [2,3,4],
             [3,4,5],
             [4,5,6]  ])

w2 = np.array([10,20,30])

# question: how do we add W matrix to each row of X seperately?
Y2 = X2

for i in range((X2).shape[0]):
    Y2[i,:] = X2[i,:] + w2 # we are not assigning Y to new pointer, we just change its elements values

print('')
print('printing other solution')
print(X2)
print(Y2)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]

printing other solution
[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]
[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]


In the above code, (in first solution) you're actually re-assigning Y to be a different value, which means it becomes a different thing and therefore requires a different pointer. That's different from replacing individual values in a list or numpy array (in the second solution).

The key difference is whether the entire variable is replaced (new location in memory) vs whether an element of the variable is changed (same location in memory).

In [36]:
import copy

X = np.array([ [1,2,3],
             [2,3,4],
             [3,4,5],
             [4,5,6]  ])

w = np.array([10,20,30])

Y = copy.deepcopy(X)
for i in range(X.shape[0]):
    Y[i,:] = X[i,:] + w # we are not assigning Y to new pointer, we just change its elements values


print(X) # so X does not change bec X and Y point to diffrent memory locations
print(Y)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]


In [37]:
Y = X + w # broadcasting helps us to do this without possible problems 
# normally, their sizes are different so linear algebra does not allow this, but Python allows 
print(Y)

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]


In [38]:
w2 = [-1,0,1]
print(X * w2)

[[-1  0  3]
 [-2  0  4]
 [-3  0  5]
 [-4  0  6]]


In [39]:
w3 = [-1,0,1,2]
# print(X * w3) # gives error bec "operands could not be broadcast together with shapes (4,3) (4,)"
# we need to be sure about their size

w3 = np.array([-1,0,1,2], ndmin = 2) # minimum number of dimensions = 2 means 2D array
print(w3.shape) # we need to transpose

print(X * w3.T) # multp (4,3) with (4,1) - not dot product, this is like pointwise multp
# similar to addition
print(X + w3.T)

print(X / w3.T)

(1, 4)
[[-1 -2 -3]
 [ 0  0  0]
 [ 3  4  5]
 [ 8 10 12]]
[[0 1 2]
 [2 3 4]
 [4 5 6]
 [6 7 8]]
[[-1.  -2.  -3. ]
 [ inf  inf  inf]
 [ 3.   4.   5. ]
 [ 2.   2.5  3. ]]


/tmp/ipykernel_18/3941802352.py:12: RuntimeWarning: divide by zero encountered in divide
  print(X / w3.T)


In [40]:
# some np operations
# Y = np.array(range(0,9)) -> instead of this
Y = np.arange(0,9)
print(Y) , print('')

# reshape
M = np.reshape(Y, (3,3)) # again secodn input is like a tuple 
print(M) , print('')

# repeat matrix into 9x3 (like repmat in matlab)
N = np.tile(M, 3) # repeat 3 times in columns
N2 = np.tile(M, (3,1)) # repeat 3 time sin row, 1 times in column
print(N) , print('')
print(N2) , print('')

# print(N2 + Y) - colud not do this bec of sizes
X = N2 + np.reshape(Y, (len(Y),1))
print(X) , print('')


[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]
 [6 7 8 6 7 8 6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [ 3  4  5]
 [ 7  8  9]
 [11 12 13]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]



(None, None)